name: food_demand_forecasting
channels:
  - default
  - conda-forge
dependencies:
  - python=3.8
  - ipykernel
  - jupyterlab
  - pip
  - plotly
  - numpy
  - pandas
  - scikit-learn
  - statsmodels=0.14.0
  - matplotlib